### ISSUE TITLE
Missing License File

### ISSUE THREAD

**Issue by pavelkouril** [kristofe/UnityGPUMarchingCubes#1]
Hello,

I'm quite interested in your GPU Marching Solutions, but I can't legally use them (or modify) in any project until I know under which license you published them.

Could you please add some license file? Ideally BSD or MIT, so I can improve the geometry marching cubes and use them without hassle in my thesis.

Regards
Pavel Kouril

**Comment by kristofe** [comment]
just added one.  good luck with your thesis.
