### ISSUE TITLE
Can't get it working in 5.6.1

### ISSUE THREAD

**Issue by Parilar** [kristofe/UnityGPUMarchingCubes#3]
Hey,
i can't get your project working in Unity 5.6.1.
Got several errors that scripts are missing

**Comment by kristofe** [comment]
Can you supply the error messages? Can you also supply the OS version and any other platform specific info?  I don't have unity installed anymore.

**Comment by Parilar** [comment]
First i had to upgrade the project from 5.0 to 5.6.1.
When i opened the Scene the following warnings appear :
- The referenced script on this Behaviour is missing!
- The referenced script on this Behaviour (Game Object 'ViewVolume') is missing!

**Comment by kristofe** [comment]
sorry. i can't help you.  i don't have unity or a windows machine to debug this.  you are going to have to figure it out yourself.
